name: Release Drafter

# PROCESS
#
# 1. Enumerate all PRs in merged state
# 2. Filter out any PR labeled `skip-changelog`
# 3. Updates or creates a new release in Draft mode

# USAGE
#
# Always run on merged PRs or manually via GitHub UI for debugging purposes.
#
# see .github/release-drafter.yml for configuration

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # create release in draft mode
    steps:
      - uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5.20.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
